

username=admin&password=000000&authType=password


###

POST http://localhost:8080/cas/v1/tickets/TGT-3-Q1nosIjGUeNweOeZHs9wKtZdJThJAxhanuERgliV61objGBOJ-AUJ0lcxZH9ASBw9bIcodefan-pc
Accept: */*
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

service=http://localhost/app1

<> 2021-03-24T021159.200.txt

###

GET http://localhost:8080/cas/p3/serviceValidate?service=http://localhost/app1&ticket=ST-1-eG3Kv34xFmZ7c35HrwZhmOdf4NYcodefan-pc
Accept: application/json

###
